# Generated by Django 5.1 on 2024-09-14 08:36

import blog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='username',
            field=models.SlugField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('title', models.CharField(help_text='max: 240', max_length=240, unique=True)),
                ('order', models.DateTimeField(default=blog.models.make_order)),
                ('id', models.SlugField(default='7vt5ifu9', primary_key=True, serialize=False, unique=True)),
                ('pre_content', models.TextField(help_text='max: 80000', max_length=80000, verbose_name='Body')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('content', models.TextField(max_length=1700)),
                ('order', models.DateTimeField(default=blog.models.make_order)),
                ('id', models.SlugField(default='qncdyg4knwgs5p2rjr', primary_key=True, serialize=False, unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogcomment')),
                ('assigned_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
