# Generated by Django 5.1 on 2024-08-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_bloguser_username_blogpost_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.SlugField(default='v18nj8qd', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='order',
            field=models.FloatField(default=1724561324.17307),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pre_content',
            field=models.TextField(max_length=80000),
        ),
    ]
