# Generated by Django 5.1 on 2024-09-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='id',
            field=models.SlugField(default='s2i7sw5r5kp83dc0sb', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.SlugField(default='6ii7yiup', primary_key=True, serialize=False, unique=True),
        ),
    ]
