# Generated by Django 5.1 on 2024-08-24 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='username',
            field=models.SlugField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('title', models.CharField(max_length=240, unique=True)),
                ('order', models.FloatField()),
                ('id', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('pre_content', models.TextField(max_length=20000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1700)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('assigned_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='blog.blogpost')),
            ],
        ),
    ]
