# Generated by Django 5.1 on 2024-08-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_id_alter_blogpost_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.SlugField(default='qxqxxzwj', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='order',
            field=models.FloatField(default=1724632238.98789),
        ),
    ]
