# Generated by Django 5.1 on 2024-08-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_id_alter_blogpost_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.SlugField(default='cjpnqq2n', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='order',
            field=models.FloatField(default=1724661543.713156),
        ),
    ]
