# Generated by Django 5.1 on 2024-08-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogcomment_order_alter_blogcomment_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='id',
            field=models.SlugField(default='12xm7802', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.SlugField(default='1t599y1z', primary_key=True, serialize=False, unique=True),
        ),
    ]
