# Generated by Django 5.1 on 2024-08-27 08:44

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogcomment_id_alter_blogpost_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='id',
            field=models.SlugField(default='j9bhv4tc', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='order',
            field=models.DateTimeField(default=blog.models.make_order),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.SlugField(default='bijvbz1s', primary_key=True, serialize=False, unique=True),
        ),
    ]
