# Generated by Django 5.1 on 2024-08-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogcomment_id_alter_blogcomment_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='id',
            field=models.SlugField(default='dxjb65x2', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.SlugField(default='uhrx98kt', primary_key=True, serialize=False, unique=True),
        ),
    ]
