# Generated by Django 5.1 on 2024-09-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blogpost_options_blogcomment_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='id',
            field=models.SlugField(default='6c7dk2wz110su7uc41', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.SlugField(default='vkgsnxiq', primary_key=True, serialize=False, unique=True),
        ),
    ]
